language: node_js
node_js: 16.13.2
cache: npm
notifications:
  slack:
    secure: I7+Z4WiY8/zi6umGWmrymsO04c6UenJtKG9maX8ljqk9Sz/f9n9MywKejt7btFN48z40IYMqMsVB+dwV9XhYZaFEANsiUXEDqVx7oDm8Kbcx0je1QKFUq2XjaFiHQYcjy42/XaDMwbq1zzfn9ZN2nKqHrGJ70lKQ7BXwoxdp+2clHWzqAsYYVcGUCg065LCG8wwaTIFhAFS5oLKZxbySDHzXSDyrgUFSMhyw62/P6O24TZylmoVvHTyegRXjUP0nqo30cvTWI8u1tRcTWaeNqd9Ky90AaaFsr8TOut/eaZZnEKSDB4oqE71zjrGDqSOAvKxhkhtw5BJJrapRaG+OzATHaauqhO30f7xQVF55n+ky0x/HLZ1qlaxgf9OSt9UPW9tF+T+gfPKu7Hljmebr+CmS4MOWmr89yUpMbOVug2Scuw54+70z/cwoZ4plnp67XkLqJL1tUyYwbw7UYP+esrm9lgY4jp6oJg895WJGvrTxPY8X5TxOI1Sw2Su2GnS14aiONF8n26Plc8VJlw9Xnl/Yfw+BecKiPri7VaR09wOE/aCQz9AwICGjJICUFlFGcSzkTlzMyH2V0b4OnKJvmRCjsPCTmN0hOumnbH2sHj0dDTiggfqOSoRfT/jD3R+xAdfZfQVjArh8b1XpqdM1hzb+Wk5Y5HpfakC6b+661GE=
  email: false
script:
- npm run lint
- npm run build
