language: node_js
node_js: 14.15.1
cache: npm
notifications:
  slack:
    secure: Em2PDlfWkYjwI7coagSNvhV/x3IOrreKlRXoKfCAxJAMyAHmLBUeymQYpzbau2dcsHp2+FfpsxQeZB3lWdk9R80HPhEUIALyy0f6nMBfOHaaKd23jq2rxYnzEWRyYUfuX1GQfMx1XC/uoKvKWHVprJvHfC9QZ7VYAcHsbWhJzWt4mGBpfJwoeLApcNXRT9DeWsMqYsDVhLGIbvRR7rs6WZxUNQ7ZVLGzkEU7r+/neFesnWVSd8Zdea2zut7YdET4UZcdRR+jMYA2SIlzINrKUUF3WLPkbvCeZqX1nLliCn5De5301uBJvVghrf47ybX9jxMGOvEfgui85qDdyv+LhvduAjWBA4zr9rqTeFupjDSvC9k3h7qafMYP8l+ygHrzJTsblPQifn3AFBCxdSoK4IrN8yqGLdAKFEyMAr8Hkq2lBIMycBNU8HJSlPxfH9qXBIv9ACVIlumFQDGumpuUKTQ7om7WrdNuEBk9Nw1pNJ1V2ul7d5kkBPFvROF7lhwr1Q9dsvjK4cdaV4vy4vuIfLeBRjI51vP3NmqmCikpeDAYmYNfHSiEM2mZuci+p4k1aO0mtLGVfPoBoFjs0CZV9rx6xQbbhqIDd18YtWTmEfumjvRofH1nfzDAd/I7XqAhl8ua5Cec8/bPPe+4dGRm0eJHig3shlM2sF1Gfat3Ji0=
  email: false
script:
  - npm run lint
  - npm run build
